# Generated by Django 5.2 on 2025-07-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown Course', max_length=100)),
                ('code', models.CharField(default='N/A', max_length=10)),
                ('instructor', models.CharField(default='Unknown Instructor', max_length=100)),
            ],
        ),
    ]
