# Generated by Django 5.2 on 2025-05-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_manipulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
