# Generated by Django 5.2 on 2025-06-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_manipulation', '0002_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='Unknown Instructor', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='Unknown Course', max_length=100),
        ),
    ]
